
"use client";

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FeedPost, FeedPostType } from "./FeedPost";

export { type FeedPostType };

const followingFeed: FeedPostType[] = [
    {
        author: "Helios",
        handle: "helios.tez",
        avatar: "https://placehold.co/100x100.png",
        avatarHint: "sun god",
        content: "Just published a new paper on decentralized energy grids. The future is bright and powered by the community. #solarpunk #sustainability",
        comments: 25,
        reposts: 15,
        likes: 120,
    }
];

const communitiesFeed: FeedPostType[] = [
    {
        author: "Art-AI Collective",
        handle: "art-ai.dao",
        avatar: "https://placehold.co/100x100.png",
        avatarHint: "abstract art",
        content: "Our new collaborative exhibition, 'Cyberdelic Dreams', is now open in the virtual gallery. Come and experience art generated by collective consciousness. #aiart #community",
        comments: 50,
        reposts: 30,
        likes: 250,
    }
];

export function FeedWidget({ initialFeed }: { initialFeed: FeedPostType[] }) {
  const [activeFilter, setActiveFilter] = useState<'all' | 'following' | 'communities'>('all');
  
  const feedData = {
    all: initialFeed,
    following: followingFeed,
    communities: communitiesFeed,
  };

  const currentFeed = feedData[activeFilter];

  return (
    <div>
        <div className="flex items-center gap-2 mb-4">
            <Button 
                variant={activeFilter === 'all' ? 'secondary' : 'ghost'} 
                className="rounded-full"
                onClick={() => setActiveFilter('all')}
            >
                All
            </Button>
            <Button 
                variant={activeFilter === 'following' ? 'secondary' : 'ghost'} 
                className="rounded-full"
                onClick={() => setActiveFilter('following')}
            >
                Following
            </Button>
            <Button 
                variant={activeFilter === 'communities' ? 'secondary' : 'ghost'} 
                className="rounded-full"
                onClick={() => setActiveFilter('communities')}
            >
                Communities
            </Button>
        </div>
        <div className="space-y-4">
            {currentFeed.length > 0 ? (
                currentFeed.map((item, index) => (
                    <FeedPost key={`${activeFilter}-${item.handle}-${index}`} post={item} />
                ))
            ) : (
                <Card className="glass-card rounded-2xl p-8 text-center">
                    <p className="text-muted-foreground">No posts in this category yet.</p>
                </Card>
            )}
        </div>
    </div>
  );
}
